defaults:
  - model: xgb
  - opt: ea_opt
  - eval: pareto
  - xai: pdp
  - _self_

main_path: /home/dbotache/datasets/kite/parameter_designs
splitfolder: train_80perc_test_20perc
file_name: Beispiel_Maschine_KI_Databasis

random_seed: 42

train_models: False
find_pareto: False
regression_evaluation: False
explain_regression: False
optimisation_evaluation: True
validation_results: False

output_dir: ./output
hydra:
  job:
    chdir: True
  run:
    dir: ${output_dir}
